# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ming\Desktop\2021_Lin_course\Hw1\Hw1_q5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(297, 479)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 221, 351))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.problem1 = QtWidgets.QPushButton(self.groupBox)
        self.problem1.setObjectName("problem1")
        self.gridLayout.addWidget(self.problem1, 0, 0, 1, 1)
        self.problem3 = QtWidgets.QPushButton(self.groupBox)
        self.problem3.setObjectName("problem3")
        self.gridLayout.addWidget(self.problem3, 2, 0, 1, 1)
        self.problem2 = QtWidgets.QPushButton(self.groupBox)
        self.problem2.setObjectName("problem2")
        self.gridLayout.addWidget(self.problem2, 1, 0, 1, 1)
        self.problem4 = QtWidgets.QPushButton(self.groupBox)
        self.problem4.setObjectName("problem4")
        self.gridLayout.addWidget(self.problem4, 3, 0, 1, 1)
        self.problem5 = QtWidgets.QPushButton(self.groupBox)
        self.problem5.setObjectName("problem5")
        self.gridLayout.addWidget(self.problem5, 5, 0, 1, 1)
        self.select_Num = QtWidgets.QLineEdit(self.groupBox)
        self.select_Num.setObjectName("select_Num")
        self.gridLayout.addWidget(self.select_Num, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 297, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "VGG16 TEST"))
        self.problem1.setText(_translate("MainWindow", "1. Show Train Image"))
        self.problem3.setText(_translate("MainWindow", "3. Show Model Architecture"))
        self.problem2.setText(_translate("MainWindow", "2. Show HyperParameter"))
        self.problem4.setText(_translate("MainWindow", "4. Show Training History"))
        self.problem5.setText(_translate("MainWindow", "5. Test"))
